# permissions for end users to edit pvmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pvmonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvmonitor
    app.kubernetes.io/part-of: pvmonitor
    app.kubernetes.io/managed-by: kustomize
  name: pvmonitor-editor-role
rules:
- apiGroups:
  - xinyu.com
  resources:
  - pvmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xinyu.com
  resources:
  - pvmonitors/status
  verbs:
  - get
