---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xinyu.com
  resources:
  - pvmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xinyu.com
  resources:
  - pvmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - xinyu.com
  resources:
  - pvmonitors/status
  verbs:
  - get
  - patch
  - update
