apiVersion: xinyu.com/v1
kind: PvMonitor
metadata:
  labels:
    app.kubernetes.io/name: pvmonitor
    app.kubernetes.io/instance: pvmonitor-sample
    app.kubernetes.io/part-of: pvmonitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pvmonitor
  name: pvmonitor-sample
  namespace: test
spec:
  regex: ".*"
  frequency: 300
  capacity: 80%
  email:
    host: "smtp.qiye.aliyun.com"
    port: 465
    user: "bigdata.service@sunmi.com"
    password: "Sunmi@2021bigdata"
    subject: "容量告警"
    to:
      - jixinyu@sunmi.com
      - 848280118@qq.com
    cc:
      - 848280118@qq.com